### ISSUE TITLE
Concept To-Do List

### ISSUE THREAD

**Issue by BeastKevon** [BeastKevon/Carcer#1]
- [ ] Finalize Classes - Passives | Lore(If Any) | Balancing

- [ ] Create Monsters

- [ ] Create Skills - Attacks | Magic

- [ ] Create NPCs - Selling System | Currency | Items | Story
